### ISSUE TITLE
Error when i've start

### ISSUE THREAD

**Issue by luisadha** [Akib-Vijapura/ChatBotX#3]
Error: Request failed with status code 429
    at createError (/data/data/com.termux/files/home/ChatBotX/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/data/data/com.termux/files/home/ChatBotX/node_modules/axios/lib/core/settle.js:17:12)                               at IncomingMessage.handleStreamEnd (/data/data/com.termux/files/home/ChatBotX/node_modules/axios/lib/adapters/http.js:322:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  config: {
    transitional: {                                                   silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false                                    },
    adapter: [Function: httpAdapter],                               transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,

**Comment by Akib-Vijapura** [comment]
Absolutely, I've encountered the same issue. It could be related to the OpenAI API. Currently, it seems that there aren't loggers supporting multiple requests simultaneously. I'm actively working on resolving this error. If you happen to discover a solution, please share it here.
